ACTIONS = {
    "developer.search": "Pesquisar código",
    "developer.read": "Ler arquivo",
    "developer.write": "Gravar arquivo",
    "developer.patch": "Alterar trecho",
    "developer.compile": "Compilar projeto",
    "developer.validate": "Validar projeto",
    "developer.rollback": "Rollback",
    "developer.create_file": "Criar arquivo",
    "developer.delete_file": "Excluir arquivo",
    "developer.move_file": "Mover arquivo",
    "developer.rename_file": "Renomear arquivo",
    "developer.mkdir": "Criar diretório",
    "developer.run_tests": "Executar testes",
    "developer.git_status": "Git Status",
    "developer.git_commit": "Git Commit",
    "developer.git_push": "Git Push",
    "developer.deploy": "Deploy",
}
